/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Ireport.FacturaIreport;
import Util.Definicoes;
import java.io.File;
import java.util.GregorianCalendar;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import iva.OperacoesIva;

/**
 *
 * @author celso
 */
public class BuscarListaSaidaProdutoView extends javax.swing.JFrame {

    /**
     * Creates new form SaftView
     */
    private JFileChooser fileChooser = new JFileChooser();

    public BuscarListaSaidaProdutoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        dataInicio = new com.toedter.calendar.JDateChooser();
        dataFim = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        btnImprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Lista de Saida de Produto");
        setResizable(false);

        jLabel1.setText("Data Inicio");

        jLabel2.setText("Data Inicio");

        btnImprimir.setBackground(new java.awt.Color(255, 255, 255));
        btnImprimir.setText("Imprimir");
        btnImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(46, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataFim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnImprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirActionPerformed
        // TODO add your handling code here:
        try {

            FacturaIreport.saidaProduto(getDataFacturaInicio(), getDataFacturaFim());
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e, "Erro!", 2);
        }
    }//GEN-LAST:event_btnImprimirActionPerformed
    public String getDataFacturaInicio() {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(dataInicio.getDate());
        String dataSelecionada = gc.get(GregorianCalendar.YEAR) + "-"
                + ((gc.get(GregorianCalendar.MONTH) + 1) < 10 ? "0" + (gc.get(GregorianCalendar.MONTH) + 1) : (gc.get(GregorianCalendar.MONTH) + 1)) + "-"
                + (gc.get(GregorianCalendar.DATE) < 10 ? "0" + gc.get(GregorianCalendar.DATE) : gc.get(GregorianCalendar.DATE));

        return dataSelecionada;
    }

    public String getDataFacturaFim() {
        GregorianCalendar gc = new GregorianCalendar();
        gc.setTime(dataFim.getDate());
        String dataSelecionada = gc.get(GregorianCalendar.YEAR) + "-"
                + ((gc.get(GregorianCalendar.MONTH) + 1) < 10 ? "0" + (gc.get(GregorianCalendar.MONTH) + 1) : (gc.get(GregorianCalendar.MONTH) + 1)) + "-"
                + (gc.get(GregorianCalendar.DATE) < 10 ? "0" + gc.get(GregorianCalendar.DATE) : gc.get(GregorianCalendar.DATE));

        return dataSelecionada;
    }

    public void gerarXML(File file) {
        Definicoes.file = file;

        OperacoesIva operacoesIva = new OperacoesIva();
        operacoesIva.setDataInicio(getDataFacturaInicio());
        operacoesIva.setDataFinal(getDataFacturaFim());

        operacoesIva.dadosOperacoes();
    }

    public void gerarJSON() {
//         OperacoesIva operacoesIva = new OperacoesIva(BDConexao.getBDConetion());
//         operacoesIva.setDataInicio(getDataFacturaInicio());
//         operacoesIva.setDataFinal(getDataFacturaFim());
//         operacoesIva.dadosOperacoes();
//         System.out.println("data Inicio: " + operacoesIva.getDataInicio());
//         System.out.println("data Fim: " + operacoesIva.getDataFinal());
//
//         Gson gson = new Gson();
//
//        // converte objetos Java para JSON e retorna JSON como String
//        String json = gson.toJson(operacoesIva.getDadosFacturaIva());
//
//           XStream xstream = new XStream(new DomDriver());
//    
////       DadosFacturaIva.AuditFile file = dadosFacturaIva.getAuditFile();
//          String xml = xstream.toXML(json);
//        
//        try 
//        {
//            //Escreve Json convertido em arquivo chamado "file.json"
//            LocalDate date = LocalDate.now();
//            FileWriter writer = new FileWriter("arquivos_xml/file_"+date+"_Saft.json");
//            
////            System.out.println(""+writer.getEncoding().);
//            writer.write(json);
//            writer.close();
//
//        } catch (IOException e) {
//            e.printStackTrace();
//        }
//
//        System.out.println(json);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarListaSaidaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarListaSaidaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarListaSaidaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarListaSaidaProdutoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarListaSaidaProdutoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImprimir;
    private com.toedter.calendar.JDateChooser dataFim;
    private com.toedter.calendar.JDateChooser dataInicio;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
